In [2]:
# Import libraries
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt
import glob
import os

**UPLOAD DATA CSV**

In [3]:
# Mount in Google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [66]:
filepaths_Aurora = [f for f in os.listdir(".") if f.endswith('Aurora.csv')]
df_Aurora = pd.concat(map(pd.read_csv, filepaths_Aurora))
df_Aurora

ACC_X     ACC_Y     ACC_Z   GYR_X    GYR_Y  GYR_Z  label
0   -0.997070 -1.998047  1.490234  218.75 -101.375  185.5    2.0
1   -0.997070 -1.998047  1.490234  218.75 -101.375  185.5    2.0
2   -0.997070 -1.998047  1.490234  218.75 -101.375  185.5    2.0
3   -0.997070 -1.998047  1.490234  218.75 -101.375  185.5    2.0
4   -0.997070 -1.998047  1.490234  218.75 -101.375  185.5    2.0
..        ...       ...       ...     ...      ...    ...    ...
395 -1.351562  1.646484 -1.792969  206.50  211.250  239.5    0.0
396 -1.359375  1.628906 -1.772461  206.50  211.250  239.5    0.0
397 -1.359375  1.628906 -1.772461  206.50  211.250  239.5    0.0
398 -1.359375  1.628906 -1.772461  206.50  211.250  239.5    0.0
399 -1.359375  1.628906 -1.772461  206.50  211.250  239.5    0.0

[12000 rows x 7 columns]

In [57]:
filepaths_Letizia = [f for f in os.listdir(".") if f.startswith('Letizia')]
df_Letizia = pd.concat(map(pd.read_csv, filepaths_Letizia))
df_Letizia

ACC_X     ACC_Y     ACC_Z   GYR_X    GYR_Y    GYR_Z  label
0    1.025391  1.804688 -0.923828 -181.25  176.000  143.750    2.0
1    1.025391  1.804688 -0.923828 -181.25  176.000  143.750    2.0
2    1.025391  1.804688 -0.923828 -181.25  176.000  143.750    2.0
3    1.025391  1.804688 -0.923828 -181.25  176.000  143.750    2.0
4    1.025391  1.804688 -0.923828 -181.25  176.000  143.750    2.0
..        ...       ...       ...     ...      ...      ...    ...
395 -1.590820  1.369141 -1.825195  188.00 -231.250 -234.875    0.0
396 -1.590820  1.369141 -1.825195  188.00 -231.250 -234.875    0.0
397 -1.590820  1.369141 -1.825195  188.00 -231.250 -234.875    0.0
398 -1.590820  1.369141 -1.825195  188.00 -231.250 -234.875    0.0
399 -1.600586  1.347656 -1.835938  184.50 -231.375 -233.875    0.0

[12000 rows x 7 columns]

In [58]:
filepaths_Natalia = [f for f in os.listdir(".") if f.endswith('Natalia.csv')]
df_Natalia = pd.concat(map(pd.read_csv, filepaths_Natalia))
df_Natalia

ACC_X     ACC_Y     ACC_Z   GYR_X  GYR_Y   GYR_Z  label
0   -1.373047  1.105469  1.671875  -80.25  131.0  205.00    1.0
1   -1.373047  1.105469  1.671875  -80.25  131.0  205.00    1.0
2   -1.373047  1.105469  1.671875  -80.25  131.0  205.00    1.0
3   -1.373047  1.105469  1.671875  -80.25  131.0  205.00    1.0
4   -1.373047  1.105469  1.671875  -80.25  131.0  205.00    1.0
..        ...       ...       ...     ...    ...     ...    ...
395 -1.688477  1.052734  1.644531  205.00 -166.5 -218.25    1.0
396 -1.688477  1.052734  1.644531  205.00 -166.5 -218.25    1.0
397 -1.688477  1.052734  1.644531  205.00 -166.5 -218.25    1.0
398 -1.688477  1.052734  1.644531  205.00 -166.5 -218.25    1.0
399 -1.688477  1.052734  1.644531  205.00 -166.5 -218.25    1.0

[12000 rows x 7 columns]

In [59]:
filepaths_Adelaide = [f for f in os.listdir(".") if f.endswith('Adelaide.csv')]
df_Adelaide = pd.concat(map(pd.read_csv, filepaths_Adelaide))
df_Adelaide

ACC_X     ACC_Y     ACC_Z    GYR_X   GYR_Y   GYR_Z  label
0   -1.816406  1.111328 -1.414062  207.500 -152.00  198.25    0.0
1   -1.816406  1.111328 -1.414062  207.500 -152.00  198.25    0.0
2   -1.816406  1.111328 -1.404297  210.500 -152.50  199.00    0.0
3   -1.816406  1.111328 -1.404297  210.500 -152.50  199.00    0.0
4   -1.816406  1.111328 -1.404297  210.500 -152.50  199.00    0.0
..        ...       ...       ...      ...     ...     ...    ...
395 -1.416992  1.107422  1.820312 -150.625   99.25  237.25    1.0
396 -1.416992  1.107422  1.820312 -150.625   99.25  237.25    1.0
397 -1.416992  1.107422  1.820312 -150.625   99.25  237.25    1.0
398 -1.416992  1.107422  1.820312 -150.625   99.25  237.25    1.0
399 -1.416992  1.107422  1.820312 -150.625   99.25  237.25    1.0

[12000 rows x 7 columns]

***CHECK FOR MEANINGFUL PATTERNS WITHIN RAW DATA (means)***

In [10]:
gb_auro = df_Aurora.groupby("label")
gb_leti = df_Letizia.groupby("label")
gb_nati = df_Natalia.groupby("label")
gb_ade = df_Adelaide.groupby("label")

ACQUISIZIONI AURORA

In [11]:
df_dritto_Aurora = gb_auro.get_group(0)
# Reset indexes
df_dritto_Aurora = df_dritto_Aurora.reset_index(drop=True)
# Replace infinite updated data with nan
df_dritto_Aurora.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_dritto_Aurora.dropna(inplace=True)
df_dritto_Aurora.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3955.000000  3955.000000  3955.000000  3955.000000  3955.000000   
mean     -0.955051     1.092683    -0.741072     8.826059   -21.981653   
std       1.316277     0.385551     1.492286   157.167288   174.900960   
min      -1.982422     0.000000    -2.000000  -250.000000  -249.875000   
25%      -1.730469     0.835938    -1.772949  -141.125000  -182.750000   
50%      -1.496094     1.154297    -1.492188    16.500000   -70.500000   
75%      -1.202148     1.388672     0.917969   143.750000   168.500000   
max       1.996094     1.937500     1.998047   249.500000   249.500000   

             GYR_Z   label  
count  3955.000000  3955.0  
mean     10.135240     0.0  
std     199.341398     0.0  
min    -250.000000     0.0  
25%    -201.875000     0.0  
50%     108.500000     0.0  
75%     207.000000     0.0  
max     249.750000     0.0

In [12]:
df_rovescio_Aurora = gb_auro.get_group(1)
# Reset indexes
df_rovescio_Aurora = df_rovescio_Aurora.reset_index(drop=True)
# Replace infinite updated data with nan
df_rovescio_Aurora.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_rovescio_Aurora.dropna(inplace=True)
df_rovescio_Aurora.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X       GYR_Y  \
count  3970.000000  3970.000000  3970.000000  3970.000000  3970.00000   
mean     -0.767331     0.985539     0.419683   -13.667916    29.42711   
std       1.522874     0.517298     1.735072   185.041152   152.63873   
min      -2.000000    -1.976562    -1.999023  -249.625000  -249.87500   
25%      -1.792969     0.822266    -1.752930  -194.250000   -73.62500   
50%      -1.617188     1.080078     1.634766   -82.375000    42.50000   
75%       1.267578     1.248047     1.863281   198.187500   165.50000   
max       1.998047     1.968750     1.998047   249.250000   248.75000   

             GYR_Z   label  
count  3970.000000  3970.0  
mean      0.322717     1.0  
std     210.639559     0.0  
min    -249.875000     1.0  
25%    -220.375000     1.0  
50%     111.000000     1.0  
75%     213.250000     1.0  
max     249.500000     1.0

In [13]:
df_battuta_Aurora = gb_auro.get_group(2)
# Reset indexes
df_battuta_Aurora = df_battuta_Aurora.reset_index(drop=True)
# Replace infinite updated data with nan
df_battuta_Aurora.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_battuta_Aurora.dropna(inplace=True)
df_battuta_Aurora.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3989.000000  3989.000000  3989.000000  3989.000000  3989.000000   
mean     -0.669279     1.196400    -0.403847   -31.323875   -72.347236   
std       1.310118     1.086653     1.362758   184.781963   160.617783   
min      -1.997070    -2.000000    -1.988281  -250.000000  -249.000000   
25%      -1.529297     1.203125    -1.325195  -206.750000  -202.375000   
50%      -1.167969     1.576172    -1.099609  -132.125000  -143.500000   
75%      -0.842773     1.791016     1.349609   163.250000    64.250000   
max       1.998047     1.996094     1.996094   249.750000   247.750000   

             GYR_Z   label  
count  3989.000000  3989.0  
mean     11.326993     2.0  
std     197.353495     0.0  
min    -249.000000     2.0  
25%    -198.500000     2.0  
50%     122.500000     2.0  
75%     204.500000     2.0  
max     249.250000     2.0

ACQUISIZIONI LETIZIA

In [14]:
df_dritto_Letizia = gb_leti.get_group(0)
# Reset indexes
df_dritto_Letizia = df_dritto_Letizia.reset_index(drop=True)
# Replace infinite updated data with nan
df_dritto_Letizia.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_dritto_Letizia.dropna(inplace=True)
df_dritto_Letizia.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3967.000000  3967.000000  3967.000000  3967.000000  3967.000000   
mean      0.169582     0.949655    -0.182160    23.689721   -48.271537   
std       1.632111     0.414215     1.691100   203.680218   146.276121   
min      -1.998047     0.000000    -1.999023  -249.625000  -249.875000   
25%      -1.771484     0.830078    -1.827148  -213.375000  -168.250000   
50%       1.070312     0.980469     0.000000   106.500000   -86.750000   
75%       1.738281     1.250000     1.781250   222.000000    28.250000   
max       1.998047     1.960938     1.998047   249.500000   249.500000   

             GYR_Z   label  
count  3967.000000  3967.0  
mean     17.579515     0.0  
std     189.378910     0.0  
min    -249.875000     0.0  
25%    -188.875000     0.0  
50%       0.000000     0.0  
75%     204.250000     0.0  
max     249.500000     0.0

In [15]:
df_rovescio_Letizia = gb_leti.get_group(1)
# Reset indexes
df_rovescio_Letizia = df_rovescio_Letizia.reset_index(drop=True)
# Replace infinite updated data with nan
df_rovescio_Letizia.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_rovescio_Letizia.dropna(inplace=True)
df_rovescio_Letizia.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3985.000000  3985.000000  3985.000000  3985.000000  3985.000000   
mean     -0.075832     0.902637     0.816197   -10.234410     6.017095   
std       1.638650     0.377860     1.445133   180.095726   121.281915   
min      -1.996094     0.000000    -1.998047  -249.500000  -249.875000   
25%      -1.713867     0.757812     0.000000  -186.000000   -13.750000   
50%       0.000000     1.003906     1.601562     0.000000     0.000000   
75%       1.746094     1.160156     1.781250   176.000000    83.250000   
max       1.998047     1.533203     1.998047   248.000000   247.750000   

             GYR_Z   label  
count  3985.000000  3985.0  
mean    -22.523714     1.0  
std     205.593201     0.0  
min    -249.875000     1.0  
25%    -223.500000     1.0  
50%    -106.875000     1.0  
75%     222.250000     1.0  
max     249.750000     1.0

In [16]:
df_battuta_Letizia = gb_leti.get_group(2)
# Reset indexes
df_battuta_Letizia = df_battuta_Letizia.reset_index(drop=True)
# Replace infinite updated data with nan
df_battuta_Letizia.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_battuta_Letizia.dropna(inplace=True)
df_battuta_Letizia.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3986.000000  3986.000000  3986.000000  3986.000000  3986.000000   
mean     -1.164826     0.969739    -0.377402   -46.871488   -48.202741   
std       0.960580     1.318058     1.258700   171.495860   158.756632   
min      -1.999023    -1.998047    -1.991211  -249.625000  -249.500000   
25%      -1.637695     1.226074    -1.313477  -188.000000  -182.500000   
50%      -1.447266     1.486328    -0.959961  -124.625000  -113.875000   
75%      -1.205078     1.720703     1.056641   133.250000    87.000000   
max       1.994141     1.998047     1.994141   247.250000   249.500000   

             GYR_Z   label  
count  3986.000000  3986.0  
mean     16.290940     2.0  
std     184.948706     0.0  
min    -249.875000     2.0  
25%    -190.000000     2.0  
50%      35.500000     2.0  
75%     208.750000     2.0  
max     249.750000     2.0

ACQUISIZIONI NATALIA

In [17]:
df_dritto_Natalia = gb_nati.get_group(0)
# Reset indexes
df_dritto_Natalia = df_dritto_Natalia.reset_index(drop=True)
# Replace infinite updated data with nan
df_dritto_Natalia.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_dritto_Natalia.dropna(inplace=True)
df_dritto_Natalia.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3989.000000  3989.000000  3989.000000  3989.000000  3989.000000   
mean     -1.354076     1.190957    -0.218401    27.834404   -29.395870   
std       0.514042     0.391009     1.784653   163.611217   162.093057   
min      -1.987305    -1.935547    -1.999023  -249.250000  -249.750000   
25%      -1.591797     0.964844    -1.812500  -148.500000  -182.250000   
50%      -1.417969     1.212891    -1.576172    87.750000   -72.125000   
75%      -1.199219     1.433594     1.812500   171.000000   124.500000   
max       1.900391     1.867188     1.998047   246.750000   249.500000   

             GYR_Z   label  
count  3989.000000  3989.0  
mean     -1.843194     0.0  
std     198.619518     0.0  
min    -249.750000     0.0  
25%    -201.125000     0.0  
50%     -98.000000     0.0  
75%     203.500000     0.0  
max     248.750000     0.0

In [18]:
df_rovescio_Natalia = gb_nati.get_group(1)
# Reset indexes
df_rovescio_Natalia = df_rovescio_Natalia.reset_index(drop=True)
# Replace infinite updated data with nan
df_rovescio_Natalia.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_rovescio_Natalia.dropna(inplace=True)
df_rovescio_Natalia.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3990.000000  3990.000000  3990.000000  3990.000000  3990.000000   
mean     -1.470884     1.214832     1.167120   -43.456328    69.821476   
std       0.341146     0.246576     1.259400   177.436186   141.797426   
min      -1.981445     0.636719    -2.000000  -249.750000  -249.875000   
25%      -1.679688     1.054688     1.527344  -193.000000   -36.500000   
50%      -1.486328     1.152344     1.658203  -147.375000   129.000000   
75%      -1.276367     1.375000     1.761719   150.250000   184.500000   
max       1.972656     1.916016     1.998047   249.500000   248.000000   

             GYR_Z   label  
count  3990.000000  3990.0  
mean     13.228289     1.0  
std     217.065203     0.0  
min    -250.000000     1.0  
25%    -218.125000     1.0  
50%     175.500000     1.0  
75%     225.500000     1.0  
max     249.500000     1.0

In [19]:
df_battuta_Natalia = gb_nati.get_group(2)
# Reset indexes
df_battuta_Natalia = df_battuta_Natalia.reset_index(drop=True)
# Replace infinite updated data with nan
df_battuta_Natalia.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_battuta_Natalia.dropna(inplace=True)
df_battuta_Natalia.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3990.000000  3990.000000  3990.000000  3990.000000  3990.000000   
mean     -1.108621    -0.096122    -0.845989    15.540962   -98.487594   
std       0.666393     1.805466     1.175723   205.203208   179.503482   
min      -1.994141    -1.998047    -1.990234  -248.875000  -249.875000   
25%      -1.371094    -1.838867    -1.528076  -200.500000  -223.406250   
50%      -1.136719    -1.594727    -1.264648   158.250000  -198.250000   
75%      -1.001953     1.814453    -0.949219   211.750000    15.000000   
max       1.998047     1.998047     1.992188   249.750000   249.750000   

             GYR_Z   label  
count  3990.000000  3990.0  
mean      7.973997     2.0  
std     221.358082     0.0  
min    -249.750000     2.0  
25%    -221.000000     2.0  
50%     152.250000     2.0  
75%     230.500000     2.0  
max     248.750000     2.0

ACQUISIZIONI ADELAIDE

In [20]:
df_dritto_Adelaide = gb_ade.get_group(0)
# Reset indexes
df_dritto_Adelaide = df_dritto_Adelaide.reset_index(drop=True)
# Replace infinite updated data with nan
df_dritto_Adelaide.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_dritto_Adelaide.dropna(inplace=True)
df_dritto_Adelaide.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3989.000000  3989.000000  3989.000000  3989.000000  3989.000000   
mean     -0.971031     1.159266    -1.485142    65.442655   -55.213415   
std       1.317592     0.231849     0.656478   193.677914   162.875944   
min      -2.000000     0.421875    -2.000000  -250.000000  -249.500000   
25%      -1.707031     1.027344    -1.744141  -173.875000  -190.500000   
50%      -1.531250     1.203125    -1.585938   178.000000  -136.000000   
75%      -1.262695     1.314453    -1.439453   215.000000   108.000000   
max       1.998047     1.660156     1.998047   249.750000   247.250000   

             GYR_Z   label  
count  3989.000000  3989.0  
mean     11.064662     0.0  
std     195.230063     0.0  
min    -249.625000     0.0  
25%    -206.750000     0.0  
50%     -10.250000     0.0  
75%     201.000000     0.0  
max     249.500000     0.0

In [21]:
df_rovescio_Adelaide = gb_ade.get_group(1)
# Reset indexes
df_rovescio_Adelaide = df_rovescio_Adelaide.reset_index(drop=True)
# Replace infinite updated data with nan
df_rovescio_Adelaide.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_rovescio_Adelaide.dropna(inplace=True)
df_rovescio_Adelaide.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  4000.000000  4000.000000  4000.000000  4000.000000  4000.000000   
mean     -1.039340     1.109400     0.883181   -50.521969    50.477047   
std       1.253541     0.239416     1.421021   174.886349   130.869067   
min      -1.995117     0.347656    -1.997070  -250.000000  -249.625000   
25%      -1.711914     0.964844     1.295898  -199.750000    -6.000000   
50%      -1.491211     1.146484     1.548828  -142.500000    79.750000   
75%      -1.316406     1.259766     1.730469   125.062500   165.250000   
max       1.994141     1.640625     1.998047   249.750000   249.250000   

             GYR_Z   label  
count  4000.000000  4000.0  
mean     11.032469     1.0  
std     188.251046     0.0  
min    -249.750000     1.0  
25%    -182.000000     1.0  
50%     -22.625000     1.0  
75%     204.250000     1.0  
max     248.750000     1.0

In [22]:
df_battuta_Adelaide = gb_ade.get_group(2)
# Reset indexes
df_battuta_Adelaide = df_battuta_Adelaide.reset_index(drop=True)
# Replace infinite updated data with nan
df_battuta_Adelaide.replace([np.inf, -np.inf], np.nan, inplace=True)
# Drop rows with NaN
df_battuta_Adelaide.dropna(inplace=True)
df_battuta_Adelaide.describe()

ACC_X        ACC_Y        ACC_Z        GYR_X        GYR_Y  \
count  3975.000000  3975.000000  3975.000000  3975.000000  3975.000000   
mean     -0.404122     0.997528    -0.348223     5.036274   -47.986887   
std       1.385615     1.431504     1.183783   209.046380   162.302172   
min      -1.958984    -2.000000    -1.996094  -250.000000  -249.875000   
25%      -1.353516     1.207031    -1.205078  -215.000000  -181.250000   
50%      -1.148438     1.667969    -0.916016   126.750000  -118.750000   
75%       1.363281     1.865234     1.009766   213.500000   103.000000   
max       1.982422     1.998047     1.988281   249.750000   249.750000   

             GYR_Z   label  
count  3975.000000  3975.0  
mean     51.709890     2.0  
std     193.718262     0.0  
min    -250.000000     2.0  
25%    -167.250000     2.0  
50%     172.750000     2.0  
75%     217.750000     2.0  
max     249.750000     2.0

**FULL ACQUISITIONS DATASET**

In [65]:
df_Adelaide = df_Adelaide.reset_index(drop=True)
df_Adelaide.replace([np.inf, -np.inf], np.nan, inplace=True)
df_Adelaide.dropna(inplace=True)
df_Adelaide.shape

(11964, 7)

In [67]:
df_Aurora = df_Aurora.reset_index(drop=True)
df_Aurora.replace([np.inf, -np.inf], np.nan, inplace=True)
df_Aurora.dropna(inplace=True)
df_Aurora.shape

(11914, 7)

In [63]:
df_Natalia = df_Natalia.reset_index(drop=True)
df_Natalia.replace([np.inf, -np.inf], np.nan, inplace=True)
df_Natalia.dropna(inplace=True)
df_Natalia.shape

(11969, 7)

In [68]:
df_Letizia = df_Letizia.reset_index(drop=True)
df_Letizia.replace([np.inf, -np.inf], np.nan, inplace=True)
df_Letizia.dropna(inplace=True)
df_Letizia.shape

(11938, 7)

In [69]:
df_all = pd.concat([df_Aurora, df_Natalia,df_Letizia, df_Adelaide] , axis= 0)
df_all = df_all.reset_index(drop=True)
df_all.shape

(47785, 7)

In [70]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47785 entries, 0 to 47784
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ACC_X   47785 non-null  float64
 1   ACC_Y   47785 non-null  float64
 2   ACC_Z   47785 non-null  float64
 3   GYR_X   47785 non-null  float64
 4   GYR_Y   47785 non-null  float64
 5   GYR_Z   47785 non-null  float64
 6   label   47785 non-null  float64
dtypes: float64(7)
memory usage: 2.6 MB


**SPLITTING DATASET**

In [71]:
# TARGET VARIABLE = TYPE OF SHOT
y = df_all["label"]
y

0        2.0
1        2.0
2        2.0
3        2.0
4        2.0
        ... 
47780    1.0
47781    1.0
47782    1.0
47783    1.0
47784    1.0
Name: label, Length: 47785, dtype: float64

In [72]:
# EXPLANATORY VARIABLES = GYROSCOPE &  ACCELEROMETER MEASURES
X = df_all.drop("label", axis=1) 
X

ACC_X     ACC_Y     ACC_Z    GYR_X    GYR_Y   GYR_Z
0     -0.997070 -1.998047  1.490234  218.750 -101.375  185.50
1     -0.997070 -1.998047  1.490234  218.750 -101.375  185.50
2     -0.997070 -1.998047  1.490234  218.750 -101.375  185.50
3     -0.997070 -1.998047  1.490234  218.750 -101.375  185.50
4     -0.997070 -1.998047  1.490234  218.750 -101.375  185.50
...         ...       ...       ...      ...      ...     ...
47780 -1.416992  1.107422  1.820312 -150.625   99.250  237.25
47781 -1.416992  1.107422  1.820312 -150.625   99.250  237.25
47782 -1.416992  1.107422  1.820312 -150.625   99.250  237.25
47783 -1.416992  1.107422  1.820312 -150.625   99.250  237.25
47784 -1.416992  1.107422  1.820312 -150.625   99.250  237.25

[47785 rows x 6 columns]

**TRAIN & TEST**

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size =0.30,   #We are taking a test size of 25% and a train size of 75%
                                                    stratify=y,        #in order to preserve target propotions.
                                                    random_state= 123) #fix random seed for replicability
print(X_train.shape, X_test.shape)

(33449, 6) (14336, 6)


In [74]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import metrics 
from sklearn.metrics import f1_score
import math

In [99]:
# Function which reports which are the best hyperparameters for a classifier using Grid Search
# MULTICLASS CLASSIFICATION PROBLEM

def hyperp_search(classifier, parameters):
    gs = GridSearchCV(classifier, parameters, cv=3, scoring = 'f1_micro', verbose=0, n_jobs=-1)
    gs = gs.fit(X_train, y_train)
    print("f1_train: %f using %s" % (gs.best_score_, gs.best_params_))

    best_model = gs.best_estimator_
    y_pred = best_model.predict(X_test)

    print("f1_test: ", f1_score(y_test, y_pred, average = 'micro'))
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

* DECISION TREE

In [100]:
%%time
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
parameters = {'criterion': ['entropy','gini'], 
              'max_depth': [5,10, 20],
              'min_samples_split': [10,15,20],
              'min_samples_leaf': [8,10]}

hyperp_search(classifier,parameters)

f1_train: 0.972854 using {'criterion': 'entropy', 'max_depth': 20, 'min_samples_leaf': 8, 'min_samples_split': 15}
f1_test:  0.9803292410714286
[[4727   37    6]
 [ 209 4571    4]
 [  26    0 4756]]
              precision    recall  f1-score   support

         0.0       0.95      0.99      0.97      4770
         1.0       0.99      0.96      0.97      4784
         2.0       1.00      0.99      1.00      4782

    accuracy                           0.98     14336
   macro avg       0.98      0.98      0.98     14336
weighted avg       0.98      0.98      0.98     14336

CPU times: user 793 ms, sys: 63.7 ms, total: 856 ms
Wall time: 8.46 s


In [113]:
#best model according to GridSearch
model_tree = DecisionTreeClassifier(criterion = 'entropy', max_depth = 20  , min_samples_leaf =8, min_samples_split = 15)

In [114]:
model_tree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=20, min_samples_leaf=8,
                       min_samples_split=15)

* LOGISTIC REGRESSION

In [102]:
%%time 
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
parameters = {"C":[1e-4,1e-3,1e-2,1e-1,1,10], 
              "max_iter":[1000, 2000]}

hyperp_search(classifier,parameters)

f1_train: 0.564113 using {'C': 1, 'max_iter': 1000}
f1_test:  0.5583147321428571
[[2618 1295  857]
 [ 953 3326  505]
 [1860  862 2060]]
              precision    recall  f1-score   support

         0.0       0.48      0.55      0.51      4770
         1.0       0.61      0.70      0.65      4784
         2.0       0.60      0.43      0.50      4782

    accuracy                           0.56     14336
   macro avg       0.56      0.56      0.55     14336
weighted avg       0.56      0.56      0.55     14336

CPU times: user 7.53 s, sys: 5.41 s, total: 12.9 s
Wall time: 1min 18s


In [ ]:
#best model according to GridSearch
model_lr = LogisticRegression(C=1, max_iter=1000)

* SVM

In [105]:
%%time
from sklearn.svm import SVC

classifier = SVC()
parameters = {"kernel":['linear','rbf'], "C":[0.1,10,100]}

hyperp_search(classifier,parameters)

KeyboardInterrupt: ignored

In [ ]:
#best model according to GridSearch
#model_svm = SVC(C=100, kernel='rbf', probability=True)


**MAKING PREDICTIONS** --> DECISION TREE

In [176]:
filepaths_pred_Letizia = [f for f in os.listdir(".") if f.startswith('LETIZIANOLABEL_BATTUTA')]
df_pred_Letizia = pd.concat(map(pd.read_csv, filepaths_pred_Letizia))
df_pred_Letizia

ACC_X  ACC_Y  ACC_Z  GYR_X  GYR_Y  GYR_Z
0   -1.184  1.916 -1.761  195.8  -77.0  192.8
1   -1.184  1.916 -1.761  195.8  -77.0  192.8
2   -1.184  1.916 -1.761  195.8  -77.0  192.8
3   -1.184  1.916 -1.761  195.8  -77.0  192.8
4   -1.184  1.916 -1.761  195.8  -77.0  192.8
..     ...    ...    ...    ...    ...    ...
395 -1.197 -1.983 -1.653  225.8  -94.0  203.2
396 -1.197 -1.983 -1.653  225.8  -94.0  203.2
397 -1.197 -1.983 -1.653  225.8  -94.0  203.2
398 -1.197 -1.983 -1.653  226.0  -94.4  203.2
399 -1.197 -1.980 -1.640  226.0  -94.4  203.2

[2000 rows x 6 columns]

In [177]:
df_pred_Letizia.replace([np.inf, -np.inf], np.nan, inplace=True)
df_pred_Letizia.dropna(inplace=True)
df_pred_Letizia = df_pred_Letizia.reset_index(drop=True)
df_pred_Letizia.shape

(1995, 6)

In [178]:
# EXPLANATORY VARIABLES
X2 = df_pred_Letizia

In [179]:
# TARGET PREDICTED 
y2_pred = model_tree.predict(X2)

In [180]:
y2_pred_col = pd.DataFrame(y2_pred)

In [181]:
# file with predictions
pred_Leti = pd.concat([X2, y2_pred_col] , axis = 1)
pred_Leti

ACC_X  ACC_Y  ACC_Z  GYR_X  GYR_Y  GYR_Z    0
0    -1.184  1.916 -1.761  195.8  -77.0  192.8  2.0
1    -1.184  1.916 -1.761  195.8  -77.0  192.8  2.0
2    -1.184  1.916 -1.761  195.8  -77.0  192.8  2.0
3    -1.184  1.916 -1.761  195.8  -77.0  192.8  2.0
4    -1.184  1.916 -1.761  195.8  -77.0  192.8  2.0
...     ...    ...    ...    ...    ...    ...  ...
1990 -1.197 -1.983 -1.653  225.8  -94.0  203.2  2.0
1991 -1.197 -1.983 -1.653  225.8  -94.0  203.2  2.0
1992 -1.197 -1.983 -1.653  225.8  -94.0  203.2  2.0
1993 -1.197 -1.983 -1.653  226.0  -94.4  203.2  2.0
1994 -1.197 -1.980 -1.640  226.0  -94.4  203.2  2.0

[1995 rows x 7 columns]

In [182]:
pred_Leti.columns = ['ACC_X','ACC_Y','ACC_Z','GYR_X','GYR_Y','GYR_Z', 'pred']
pred_Leti

ACC_X  ACC_Y  ACC_Z  GYR_X  GYR_Y  GYR_Z  pred
0    -1.184  1.916 -1.761  195.8  -77.0  192.8   2.0
1    -1.184  1.916 -1.761  195.8  -77.0  192.8   2.0
2    -1.184  1.916 -1.761  195.8  -77.0  192.8   2.0
3    -1.184  1.916 -1.761  195.8  -77.0  192.8   2.0
4    -1.184  1.916 -1.761  195.8  -77.0  192.8   2.0
...     ...    ...    ...    ...    ...    ...   ...
1990 -1.197 -1.983 -1.653  225.8  -94.0  203.2   2.0
1991 -1.197 -1.983 -1.653  225.8  -94.0  203.2   2.0
1992 -1.197 -1.983 -1.653  225.8  -94.0  203.2   2.0
1993 -1.197 -1.983 -1.653  226.0  -94.4  203.2   2.0
1994 -1.197 -1.980 -1.640  226.0  -94.4  203.2   2.0

[1995 rows x 7 columns]

In [185]:
# save file
pred_Leti.to_csv('pred_battuta_Leti.csv')

In [184]:
# check 
pred_Leti['pred'].value_counts() 

2.0    1975
0.0      20
Name: pred, dtype: int64